# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  # Non-workspace packages - can be updated independently
  - package-ecosystem: "julia"
    directory: "/BasicPackage.jl"
    schedule:
      interval: "weekly"

  - package-ecosystem: "julia"
    directory: "/ManifestPackage.jl"
    schedule:
      interval: "weekly"

  - package-ecosystem: "julia"
    directory: "/VersionedManifestPackage.jl"
    schedule:
      interval: "weekly"

  # Workspace packages - grouped together since they share a manifest
  - package-ecosystem: "julia"
    directories:
      - "/WorkspacePackage1.jl/SubPackageA"
      - "/WorkspacePackage1.jl/SubPackageB"
    schedule:
      interval: "weekly"
    groups:
      WorkspacePackage1:
        patterns:
          - "*"

  # Workspace packages - NOT grouped together to show that the manifest isn't updated
  - package-ecosystem: "julia"
    directories:
      - "/WorkspacePackage2.jl/SubPackageA"
    schedule:
      interval: "weekly"

