name = "VersionedManifestPackage"
uuid = "33333333-3333-3333-3333-333333333333"
authors = ["Test User <test@example.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21, 1.4"
julia = "1.10"
