name = "LibraryPackage"
uuid = "12345678-1234-5678-1234-567812345679"
authors = ["Test Author"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[compat]
Graphs = "1.4.1"
JLD2 = "0.1.11, 0.2, 0.3, 0.4, 0.5, 0.6"
SimpleTraits = "0.9"
julia = "1.6"
