name = "LibraryPackage"
uuid = "12345678-1234-5678-1234-567812345679"
authors = ["Test Author"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Graphs = "1.0"
julia = "1.6"
